## Open Data in der EU

Da es sich in dieser Analyse nicht um Unternehmensdaten handelt, widmet sich dieses Kapitel statt des klassischen ***Business Understanding*** der Untersuchung, wie die Europäische Union Open Data definiert, welche Ziele die europäische Datenpolitik verfolgt und wie diese rechtlich umgesetzt werden.

### Open Data

Die Open-Data-Richtlinie der EU definiert den Zugang zu Informationen als ein Grundrecht und als die Basis für die Entwicklung innovativer Produkte und Dienstleistungen.

Ein konkreter Anwendungsfall für das ***Register der Kulturgüter*** wäre eine Tourismus-App, die sich auf kulturelle und geschichtliche Inhalte konzentriert und sie mit Daten zu Übernachtungsmöglichkeiten und Einrichtungen wie Museen verknüpft. So könnte man einen Reiseplaner umsetzen, der Routen für kulturelle Rundreisen berechnet und zusätzlich eine Funktion anbietet, die Kulturgüter in einem definierten Umkreis um den Urlaubsort anzuzeigen, z.B. für Kurzausflüge oder Tagesplanung. Da auch die Beschreibungen der Kulturgüter verfügbar sind, könnte man diese in verschiedene Sprachen übersetzen und nach Bedarf anzeigen lassen.

Eine solche App wäre als Open-Source-App denkbar oder als proprietäre App von Reiseführer-Verlagen oder Reiseanbietern.

::: {.callout-caution collapse="false" icon="false" title="{{< fa section >}} Abs (1), Artikel 5 und 8 (Auszug)"}
\(5\) \| **Der Zugang zu Informationen ist ein Grundrecht**. Die Charta der Grundrechte der Europäischen Union (im Folgenden „Charta“) bestimmt, dass jede Person das Recht auf freie Meinungsäußerung hat; dies schließt die Meinungsfreiheit und die Freiheit ein, Informationen und Ideen ohne behördliche Eingriffe und ohne Rücksicht auf Staatsgrenzen zu empfangen und weiterzugeben.

\(8\) \| [...] Die Bereitstellung dieser Informationen, die auch dynamische Daten umfassen, in einem gängigen elektronischen Format ermöglicht es Bürgern und juristischen Personen, **neue Möglichkeiten für deren Nutzung zu finden und neue, innovative Produkte und Dienstleistungen zu schaffen**. [...]

*[Directive (EU) 2019/1024 of the European Parliament and of the Council of 20 June 2019 on open data and the re-use of public sector information (recast) ; ELI: http://data.europa.eu/eli/dir/2019/1024/oj]*
:::


### INSPIRE

Die INSPIRE-Richtlinie (2007/2/EG) wurde geschaffen, um eine einheitliche europäische Geodateninfrastruktur aufzubauen und den grenzüberschreitenden Austausch von raumbezogenen Daten zu erleichtern. Durch die Harmonisierung von Datenformaten und einen verbesserten öffentlichen Zugang unterstützt sie umweltpolitische Entscheidungen und behördliche Zusammenarbeit in Europa.

In der INSPIRE-Richtlinie werden Kulturgüter den Schutzgebieten und somit den High-value Datasets zugeordnet.

::: {.callout-caution collapse="true" icon="false" title="{{< fa section >}} Anhang I: Geodaten gemäss Artikel 6 Buchstabe A, Artikel 8 Absatz 1 und Artikel 9 Buchstabe A"}

9. Schutzgebiete

Gebiete, die im Rahmen des internationalen und des gemeinschaftlichen Rechts sowie des Rechts der Mitgliedstaaten ausgewiesen sind oder verwaltet werden, um spezifische Erhaltungsziele zu erreichen.

VERORDNUNG (EG) Nr. 1089/2010 DER KOMMISSION vom 23. November 2010 zur Durchführung der Richtlinie 2007/2/EG des Europäischen Parlaments und des Rates hinsichtlich der Interoperabilität von Geodatensätzen und -diensten

*[Version 19.11.2023: Anhang II: 9. SCHUTZGEBIETE]*

[Konsolidierte Fassung vom 26.11.2024](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:02007L0002-20241126) [ELI](http://data.europa.eu/eli/dir/2007/2/2024-11-26)

[Technical Guideline zu Kulturgütern im Rahmen von INSPIRE](https://knowledge-base.inspire.ec.europa.eu/publications/inspire-data-specification-protected-sites-technical-guidelines_en)

:::


### High-Value Datasets

High-Value Datasets (HVDs) sind besonders wertvolle Datensätze des öffentlichen Sektors, deren Weiterverwendung erhebliche Vorteile für Wirtschaft, Gesellschaft und Umwelt mit sich bringt. Beispiele wie Mobilitäts-, Geolokalisierungs-, meteorologische oder Luftqualitätsdaten ermöglichen effizientere Logistik- und Verkehrsnetze, fördern Forschung und Innovation im Klimaschutz sowie eine bessere politische Entscheidungsfindung.

Die EU-Richtlinie über offene Daten verschärft daher die Vorschriften, begrenzt Gebühren, fördert die Bereitstellung in maschinenlesbaren Formaten über APIs oder Massendownloads und verpflichtet öffentliche Stellen zur kostenlosen Bereitstellung von HVDs. Laut Richtlinie sind HVDs Dokumente öffentlicher Stellen, deren Weiterverwendung mit erheblichen Vorteilen verbunden ist und die für jeden Zweck frei wiederverwendbar sein müssen.

::: {.callout-caution collapse="true" icon="false" title="{{< fa section >}} Artikel 14: Bestimmte hochwertige Datensätze und Modalitäten der Veröffentlichung und Weiterverwendung, Abs (1)"}
Solche bestimmten hochwertigen Datensätze müssen

a\) vorbehaltlich der Absätze 3, 4 und 5 kostenlos verfügbar sein,<br>
b\) maschinenlesbar sein,<br>
c\) über API verfügbar sein, und<br>
d\) gegebenenfalls als Massen-Download verfügbar sein.
:::


::: {.callout-caution collapse="true" icon="false" title="{{< fa section >}} Artikel 14: Bestimmte hochwertige Datensätze und Modalitäten der Veröffentlichung und Weiterverwendung, Abs (2)"}
\(2\) Die Ermittlung bestimmter hochwertiger Datensätze gemäß Absatz 1 beruht auf der Bewertung ihres Potenzials

a\) für die Erzielung bedeutender sozioökonomischer oder ökologischer Vorteile und innovativer Dienstleistungen,<br>
b\) für eine große Zahl von Nutzern, insbesondere KMU, von Nutzen zu sein,<br>
c\) der Erzielung von Einnahmen zu dienen, und<br>
d\) mit anderen Datensätzen kombiniert zu werden.
:::


::: {.callout-caution collapse="true" icon="false" title="{{< fa section >}} Artikel 17: Umsetzung"}
\(1\) Die Mitgliedstaaten setzen die Rechts- und Verwaltungsvorschriften in Kraft, die erforderlich sind, um dieser Richtlinie bis zum **17. Juli 2021** nachzukommen. Sie teilen der Kommission unverzüglich den Wortlaut dieser Vorschriften mit.

Bei Erlass dieser Vorschriften nehmen die Mitgliedstaaten in den Vorschriften selbst oder durch einen Hinweis bei der amtlichen Veröffentlichung auf die vorliegende Richtlinie Bezug. In diese Vorschriften fügen sie die Erklärung ein, dass Bezugnahmen in den geltenden Rechts- und Verwaltungsvorschriften auf die durch die vorliegende Richtlinie aufgehobenen Richtlinien als Bezugnahmen auf die vorliegende Richtlinie gelten. Die Mitgliedstaaten regeln die Einzelheiten dieser Bezugnahme und die Formulierung dieser Erklärung.

Die Mitgliedstaaten teilen der Kommission den Wortlaut der wichtigsten nationalen Rechtsvorschriften mit, die sie auf dem unter diese Richtlinie fallenden Gebiet erlassen.
:::


::: {.callout-caution collapse="true" icon="false" title="{{< fa section >}} Artikel 18: Bewertung durch die Kommission"}
\(1\) Frühestens am **17. Juli 2025** führt die Kommission eine Bewertung dieser Richtlinie durch und übermittelt dem Europäischen Parlament und dem Rat sowie dem Europäischen Wirtschafts- und Sozialausschuss einen Bericht über die wichtigsten Ergebnisse dieser Bewertung.

Die Mitgliedstaaten übermitteln der Kommission alle erforderlichen Angaben zur Ausarbeitung des Berichts.

\(2\) Bei der Bewertung werden insbesondere der Anwendungsbereich und die gesellschaftlichen und wirtschaftlichen Auswirkungen dieser Richtlinie geprüft, einschließlich

a\) des Steigerungsgrads der Weiterverwendung — vor allem durch KMU — von Dokumenten des öffentlichen Sektors, auf die diese Richtlinie anwendbar ist;<br>
b\) der Auswirkungen der hochwertigen Datensätze;<br>
c\) der Auswirkungen der angewandten Grundsätze für die Bemessung der Gebühren und Entgelte und der Weiterverwendung amtlicher Rechtsetzungs- und Verwaltungstexte;<br>
d\) der Weiterverwendung von Dokumenten im Besitz anderer Einrichtungen als öffentlicher Stellen;<br>
e\) der Verfügbarkeit und Verwendung von API;<br>
f\) des Zusammenwirkens der Datenschutzvorschriften und der Möglichkeiten der Weiterverwendung;<br>
g\) weiterer Möglichkeiten der Verbesserung des reibungslosen Funktionierens des Binnenmarkts und der Förderung der Entwicklung der Wirtschaft und des Arbeitsmarkts.
:::

::: {.callout-caution collapse="true" icon="false" title="{{< fa section >}} Anhang I: Liste der in Artikel 13 Absatz 1 genannten thematischen Kategorien hochwertiger Datensätze"}
1. Georaum
2. Erdbeobachtung und Umwelt
3. Meteorologie
4. Statistik
5. Unternehmen und Eigentümerschaft von Unternehmen
6. Mobilität
:::
